// Alan & Frequency Ended
// Description

// Alan Turing, the mathematician, is trying to break the encrypted messages of the German Troops, generated by their encryption device "Enigma". To find the distribution of characters, he needs to find out how many times a particular character appears in a string. But, to feed the data into his computer, "Christopher", he needs the data in lexicographic order, that is, in alphabetical order. Since, he is busy making "Christopher" better, he asks you for help. Help Alan find the frequency of characters in the encrypted strings in alphabetical order. The string contains only lower case alphabets.

// Input
// The first line contains N, the length of the string, and the next line contains the string itself.

// 1 <= N<=100

// Output
// For each unique character in the string, print the character along with its frequency in the encrypted string, separated by '-' , on a new line.

// Sample Input 1 

// 4
// aman
// Sample Output 1

// a-2
// m-1
// n-1

import java.util.Scanner;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeMap;

public class AlanAndFrequency {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int n = sc.nextInt();
        String s = sc.next();
        sc.close();

        HashMap<Character, Integer> map = new HashMap<>();
        for (int i = 0; i < n; i++) {
            char c = s.charAt(i);
            if (map.containsKey(c)) {
                map.put(c, map.get(c) + 1);
            } else {
                map.put(c, 1);
            }
        }

        TreeMap<Character, Integer> sortedMap = new TreeMap<>(map);
        for (Map.Entry<Character, Integer> elem : sortedMap.entrySet()) {
            System.out.println(elem.getKey() + "-" + elem.getValue());
        }
    }
}
